trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/v*
      - 0.1.x

pr:
  - master
  - 0.1.x

variables:
  PYTHONUNBUFFERED: 1
  ATEST_RETRIES: 2

  PY_JLST_VERSION: 0.4.0a0
  JS_JLST_VERSION: 0.4.0-a0
  JS_RJSF_VERSION: 0.4.0-a0

  FIRST_PARTY_LABEXTENSIONS: >-
    packages/jupyterlab-starters/deathbeds-jupyterlab-starters-$(JS_JLST_VERSION).tgz
    packages/jupyterlab-rjsf/deathbeds-jupyterlab-rjsf-$(JS_RJSF_VERSION).tgz

jobs:
  - template: ci/job.lint.yml
  - template: ci/job.test.yml
  - template: ci/job.combine.yml
