trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/v*

pr:
  autoCancel: false
  branches:
    - master
  paths:
    # lets us tweak binder without restarting CI
    exclude:
      - postBuild
      - environment.yml

variables:
  PYTHONUNBUFFERED: 1
  ATEST_RETRIES: 4

jobs:
  - template: ci/job.lint.yml
  - template: ci/job.test.yml
  - template: ci/job.combine.yml
