trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/v*

pr:
  - master

variables:
  PYTHONUNBUFFERED: 1
  ATEST_RETRIES: 4

jobs:
  - template: ci/job.lint.yml
  - template: ci/job.test.yml
  - template: ci/job.combine.yml
