name: jupyterlab-starters

channels:
  - conda-forge
  - defaults

dependencies:
  - cookiecutter
  - importlib_metadata
  - jupyterlab >=1.2.6,<1.3.0a0
  - nodejs >=11,<12
  - python >=3.7,<3.8.0a0
  - python-fastjsonschema
  - python-graphviz
  - ujson
