name: jupyterlab-starters-docs

channels:
  - conda-forge
  - defaults

dependencies:
  - cookiecutter
  - importlib_metadata
  - jupyterlab >=2,<2.1.0a0
  - nbsphinx >=0.5.0,<0.5.1a0
  - nodejs >=11,<12
  - pip
  - pytest
  - python >=3.7,<3.8.0a0
  - python-fastjsonschema
  - python-graphviz
  - recommonmark
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - ujson
  - pip:
      - pytest-check-links
      - sphinx-markdown-tables
